name: flutter_nested_navigation
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/HomeScreen.png
    - assets/images/SetupFlow1.png
    - assets/images/SetupFlow2.png
    - assets/images/SetupFlow3.png